version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shankara-postgres
    environment:
      POSTGRES_DB: student_activity_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shankara-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_activity_platform"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7
    container_name: shankara-mongo
    environment:
      MONGO_INITDB_Database: student_activity_platform
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shankara-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  mongo_data:

networks:
  shankara-network:
    driver: bridge
