version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shankara-postgres
    environment:
      POSTGRES_DB: student_activity_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shankara-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d student_activity_platform"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:7
    container_name: shankara-mongo
    environment:
      MONGO_INITDB_Database: student_activity_platform
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shankara-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shankara-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=student_activity_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MONGODB_URI=mongodb://mongo:27017/student_activity_platform
      - JWT_SECRET=your-jwt-secret-key
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - shankara-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shankara-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - shankara-network
    command: npm run dev

volumes:
  postgres_data:
  mongo_data:

networks:
  shankara-network:
    driver: bridge
